### ISSUE TITLE
Kotlin File showing as Java file

### ISSUE THREAD

**Issue by bpetroski** [bpetroski/travel-log-app#14]
@Pkmartus @EricWill0829  From Pull #13 
JournalListFragment File is not showing up as a Kotlin file. Looks like it may have accidently been set up as a regular java class

![image_2024-03-30_011137973](https://github.com/bpetroski/travel-log-app/assets/89823558/b305de44-5e5d-4131-aa0d-3ac06d9b31dc)

**Comment by Pkmartus** [comment]
There was an extra "}" on line 33. it'll be fixed when I commit the file after working on getting the adapter working
