### ISSUE TITLE
Journal Entry Fragment does not load placeholder image

### ISSUE THREAD

**Issue by bpetroski** [bpetroski/travel-log-app#34]
`2024-04-20 01:01:17.874 23055-23055 BitmapFactory           com.travelbetadisaster.travel_log    E  Unable to decode stream: java.io.FileNotFoundException: /data/data/com.travelbetadisaster.travel_log/files/journal_image_0.jpg: open failed: ENOENT (No such file or directory)`

should be an easy fix just gotta do the same thing we did for the journal list most likely

**Comment by Pkmartus** [comment]
yup simple enough just copied over the same logic from the list.
